### ISSUE TITLE
no errors, no output

### ISSUE THREAD

**Issue by anthonybrown** [Legitcode/redux-tutorial#2]
Hi, just started the tutorial on [reactnews](http://reactjsnews.com/your-first-redux-app/) and couldn't get my version to load so I cloned the master repo, did `npm install` and `npm start`, navigated to `localhost:8080` and nothing. There's no errors or any warnings in the command line or the console.

**Comment by zackify** [comment]
well what does the console show? It has to have something

**Comment by anthonybrown** [comment]
![screen shot 2016-03-11 at 10 30 15 am](https://cloud.githubusercontent.com/assets/1719818/13711520/018b710a-e78d-11e5-8026-589ff37765ee.png)

**Comment by anthonybrown** [comment]
![screen shot 2016-03-11 at 1 45 04 pm](https://cloud.githubusercontent.com/assets/1719818/13712039/836fd128-e78f-11e5-9d1d-fc1a36379bb5.png)

Same with `localhost:8080`

**Comment by zackify** [comment]
I'm talking about your terminal. Sorry I should have been more specific.
The server is clearly not running :)

**Comment by anthonybrown** [comment]
![screen shot 2016-03-11 at 1 49 14 pm](https://cloud.githubusercontent.com/assets/1719818/13712180/35269b0e-e790-11e5-98a4-0b8ac1647122.png)
![screen shot 2016-03-11 at 1 49 33 pm](https://cloud.githubusercontent.com/assets/1719818/13712181/3526b2b0-e790-11e5-932d-84e0e7c8e817.png)
![screen shot 2016-03-11 at 1 49 55 pm](https://cloud.githubusercontent.com/assets/1719818/13712179/352476a8-e790-11e5-9287-45230e6a6ff0.png)

**Comment by zackify** [comment]
Hmm, the output all looks fine. It is just running `webpack-dev-server` which runs all the defaults. You can see more info on it here https://webpack.github.io/docs/webpack-dev-server.html

**Comment by anthonybrown** [comment]
The thing is, it's not creating the file `bundle.js` or a `build` directory.

**Comment by anthonybrown** [comment]
![screen shot 2016-03-11 at 1 58 32 pm](https://cloud.githubusercontent.com/assets/1719818/13712409/674b6fbe-e791-11e5-96cd-172317a1b816.png)

**Comment by zackify** [comment]
It isn't supposed to, it is stored in memory. I don't use windows so I
can't figure out why the server isn't accessible. It should be from what
you've showed me.

**Comment by anthonybrown** [comment]
I'm on a mac.
When you download the repo, it runs for you?

I'll try on my iMac and see what's up.

**Comment by zackify** [comment]
Ah sorry. Yes, I even recloned, installed and did `npm start` http://localhost:8080/ has the page up.

**Comment by anthonybrown** [comment]
This is from the imac

![screen shot 2016-03-11 at 2 06 55 pm](https://cloud.githubusercontent.com/assets/1719818/13712616/a9644afa-e792-11e5-8b16-56a32b6878d3.png)

**Comment by anthonybrown** [comment]
strange, the only thing I can think of is I had nginx listening on port 8080 but I shut it down so it shouldn't be a problem.
A shame because I like the tutorial and would have loved to see it working.

**Comment by zackify** [comment]
@anthonybrown it has to be some sort of firewall maybe. Check if it is blocking that port? Also try running `./node_modules/.bin/webpack-dev-server` and see if there are any errors. I would head over to the github repo for them and see if they have any ideas since that is what isn't working. Wish it would work for you!

**Comment by anthonybrown** [comment]
@zackify, I'll try that and dig into the codebase a little more and see if I can't get to the bottom of this.

thanks for your help. :+1:

**Comment by zackify** [comment]
@anthonybrown np, I'm going to close this for now but feel free to reply.

**Comment by anthonybrown** [comment]
Just one more thing, what's up with the http://localhost:8080/webpack-dev-server/ URL that's in the output of the terminal?

**Comment by zackify** [comment]
https://webpack.github.io/docs/webpack-dev-server.html#iframe-mode iframe
mode

**Comment by anthonybrown** [comment]
@zackify :100: Cheers

**Comment by anthonybrown** [comment]
Something is broken on localhost:8080, if I use 127.0.0.1:8080, the app runs fine.
I've been working with Java/Spring and running a Tomcat server on port 8080 for work.
I'll have to look into that. Just wanted to update you on this case.

**Comment by zackify** [comment]
That's a problem with your /etc/hosts file. You probably don't have
localhost pointing to 127.0.0.1. Glad you figured it out! I would have
never guessed that.

**Comment by anthonybrown** [comment]
I do have it pointing to localhost:
    `127.0.0.1 localhost` but I also have this for Ipv6 and nginx
    `::1 localhost` and tomcat server that works on that port so it's more going on than I can figure out at the moment. Nothing is wrong with my hosts file as I can figure, I have some servers on there for work, this happened before when I was learning nginx, it's a royal pain to deal with this IPv6 server config stuff >_<

**Comment by anthonybrown** [comment]
I ran this:
    `netstat -an | grep "[.]80 .*LISTEN"`

**Comment by anthonybrown** [comment]
This is very strange, I can run `rethinkdb` on localhost:8080
I wonder if this is a node related thing where node doesn't listen to IPv6 by default?
Anyways, at least I know the tutorial works and I didn't do anything stupid lol.
I'll post if I find out what the deal is with port issues and IPv6.
